system_prompt: You are a helpful assistant for a Yahoo Fantasy Sports league manager.

# List of URLs to scrape for Yahoo Fantasy NBA news
yahoo_fantasy_news_urls:
  - https://sports.yahoo.com/nba/news/
  - https://www.nba.com/news
  - https://www.rotowire.com/basketball/articles/


# URL for Hashtag Basketball Dynasty Rankings
dynasty_rankings_url: 
  - https://hashtagbasketball.com/fantasy-basketball-dynasty-rankings

# Rotowire RSS feed URL for NBA player news
rotowire_rss_url: https://www.rotowire.com/rss/news.php?sport=NBA